-- Create the questions table
create table public.questions (
  id bigint generated by default as identity primary key,
  word_with_error text not null,
  correct_word text not null,
  explanation text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Turn on Row Level Security
alter table public.questions enable row level security;

-- Allow completely public read access to the questions table
create policy "Allow public read access to questions"
  on public.questions for read
  using (true);

-- Insert some base questions
insert into public.questions (word_with_error, correct_word, explanation) values
  ('herkez', 'herkes', 'Sonda s harfi bulunur.'),
  ('yanlız', 'yalnız', 'Kelime kökü "yalın"dan gelir (yalın-ız).'),
  ('şöför', 'şoför', 'Doğru yazımı "şoför" şeklindedir.'),
  ('kiprik', 'kirpik', 'Göz kapağının ucundaki kıllara "kirpik" denir.'),
  ('süpriz', 'sürpriz', 'Fransızca kökenli surprise kelimesinden gelir.');
